//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKR.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addressee_Numbers
    {
        public string Note { get; set; }
        public byte Phone_ID { get; set; }
        public byte Addressee_ID { get; set; }
    
        public virtual Addressee Addressee { get; set; }
        public virtual Phone_Numbers Phone_Numbers { get; set; }
    }
}
