//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKR.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datum
    {
        public long ID { get; set; }
        public byte Transducer_ID { get; set; }
        public System.DateTime DateTime { get; set; }
        public double Value { get; set; }
    
        public virtual Transducer Transducer { get; set; }
    }
}
