//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKR.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VKREntities : DbContext
    {
        public VKREntities()
            : base("name=VKREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addressee> Addressees { get; set; }
        public virtual DbSet<Addressee_Numbers> Addressee_Numbers { get; set; }
        public virtual DbSet<Datum> Data { get; set; }
        public virtual DbSet<Phone_Numbers> Phone_Numbers { get; set; }
        public virtual DbSet<System_role> System_role { get; set; }
        public virtual DbSet<Transducer> Transducers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
